"""Untitled74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3qyFxsXpT5UA247yerqFaQIUQnvwkVV
"""
#############################################################################################################################################################
#################################################################### 쿼리에서 파라미터추출  #################################################3######################
import openai 
import asyncio
from openai import AsyncOpenAI
import pandas as pd
from pydantic import BaseModel, Field, ValidationError
from typing import Literal
import thresholds
from grade_utils import map_grade_to_score, map_score_to_grade
import json
import re

df= pd.read_excel("좋은제약_거래처정보.xlsx")
markdown_table = df.to_markdown(index=False)
print(df['월'].dtype)
client = AsyncOpenAI(
    api_key=""
)

def preprocess_df(df: pd.DataFrame) -> pd.DataFrame:
    data = df.copy()
    data['월'] = pd.to_datetime(data['월'].astype(str), format='%Y%m', errors='coerce')
    return data

state = {
    "company_name": str,
    "df": pd.DataFrame,
    "start_month": str,
    "end_month": str,
    "grade_result": dict,
    "grade_report": str,
    "growth_report": str,
    "strategy_report": str
}

def clean_json_text(text: str) -> str:
    return re.sub(r"^```json\s*|\s*```$", "", text.strip(), flags=re.MULTILINE).strip()

async def parse_query_with_llm(query: str):

    prompt = f"""
너는 한국어 자연어 질의를 분석해서 병원이름(구,동포함), 시작월, 종료월을 YYYYMM 포맷으로 변환해 JSON으로 출력하는 도우미야.
출력은 JSON만 하고 설명이나 다른 텍스트는 절대 포함하지 마.

예시:
입력: '바른치과의 2011년2월에서6월까지의 실적을 분석해줘'
출력:
{{
    "company_name": "바른치과(용산구 이촌동)",
    "start_month": "201102",
    "end_month": "201106"
}}

이제 다음 입력을 처리해:
{query}
"""

    response = await client.responses.create(
        model="gpt-4.1-mini",  # 또는 gpt-4.5 / o3 모델
        input=prompt,
        temperature=0
    )
    result_text = response.output_text.strip()
    cleaned = clean_json_text(result_text)

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        raise ValueError(f"LLM이 반환한 JSON 파싱 실패: {result_text}")
    

#async def main():                                                                                            #디버깅용 (성공)
#    query = "'우리가족의원(강서구 가양동)'에서 2024년 2월 부터 2024년5월까지의 실적을 분석해줘"
#    result = await parse_query_with_llm(query)
#    print("LLM JSON 결과:", result)
#asyncio.run(main())

##############################################################################################################################################################
##############################################################################################################################################################

                                                                        # 등급선정방법1(매출수치)

def classify_company_by_revenue_estimates(company_name, df, thresholds=None, start_month=None, end_month=None):

    if thresholds is None:
        thresholds = [
            (9000000, 'S'),
            (3000000, 'A'),
            (2000000, 'B'),
            (1000000, 'C'),
            (500000,  'D'),
            (100000,  'E'),
            (0,       'F'),
        ]
    
    # 원본 보호
    data = df.copy()

    # 변환
    data['월'] = data['월'].astype(str)
    data['월'] = pd.to_datetime(data['월'], format='%Y%m', errors='coerce')

    company_rows = data[data['거래처ID'] == company_name]

    if start_month:
        start_date = pd.to_datetime(start_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] >= start_date]
    if end_month:
        end_date = pd.to_datetime(end_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] <= end_date]

    revenue_list = company_rows['매출'].tolist()
    if not revenue_list:
        return '매출없음'

    average_revenue = sum(revenue_list) / len(revenue_list)

    for figure, grade in thresholds:
        if average_revenue >= figure:
            return grade

    return '에러'

#print(classify_company_by_revenue_estimates(company_name="우리가족의원(강서구 가양동)", df=df, start_month=202402, end_month=202405)) *디버깅용(성공)

##############################################################################################################################################################
##############################################################################################################################################################

                                                                        #등급선정방법2(수익률)

def classify_company_by_profit(company_name, df, thresholds=None, start_month=None, end_month=None):

    if thresholds is None:
        thresholds = [
            (30, 'F'),
            (25, 'D'),
            (20, 'C'),
            (15, 'B'),
            (10, 'A'),
            (0, 'S')
        ]

    data = df.copy()

    # 변환
    data['월'] = pd.to_datetime(data['월'].astype(str), format='%Y%m', errors='coerce')

    company_rows = data[data["거래처ID"] == company_name]
    # 날짜로 해당 행 필터
    if start_month:
        start_date = pd.to_datetime(start_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] >= start_date]
    if end_month:
        end_date = pd.to_datetime(end_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] <= end_date]

    revenue_list = company_rows['매출'].tolist()
    expense_list = company_rows['사용 예산'].tolist()

    if not revenue_list or sum(revenue_list) == 0:
        return '데이터없음'

    total_revenue = sum(revenue_list)
    total_expense = sum(expense_list)
    profit_ratio = (total_expense / total_revenue) * 100

    for figure, grade in thresholds:
        if profit_ratio >= figure:
            return grade

    return '에러'

#print(classify_company_by_profit(company_name="우리가족의원(강서구 가양동)", df=df, start_month=202402, end_month=202405))   *디버깅용(성공)

##############################################################################################################################################################
##############################################################################################################################################################

                                                                    # 등급선정방법3(환자 수)

def classify_company_by_number_patience(company_name, df, thresholds=None, start_month=None, end_month=None):

    if thresholds is None:
        thresholds = [
            (2600, 'S'),
            (2200, 'A'),
            (1800, 'B'),
            (1400, 'C'),
            (0,    'D'),
        ]

    # 원본 보호: 복사본 사용
    data = df.copy()

    # 변환
    data['월'] = pd.to_datetime(data['월'].astype(str), format='%Y%m', errors='coerce')

    company_rows = data[data["거래처ID"] == company_name]

    if start_month:
        start_date = pd.to_datetime(start_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] >= start_date]
    if end_month:
        end_date = pd.to_datetime(end_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] <= end_date]

    number_list = company_rows['총환자수'].tolist()
    
    if not number_list:
        return '데이터없음'

    average_number = sum(number_list) / len(number_list)

    for figure, grade in thresholds:
        if average_number >= figure:
            return grade

    return '에러'

#print(classify_company_by_number_patience(company_name="우리가족의원(강서구 가양동)", df=df, start_month=202402, end_month=202405))   *디버깅용(성공)

##############################################################################################################################################################
##############################################################################################################################################################

                                                                        #등급선정방법4(거래율)

def classify_company_by_rate_interaction(company_name, df, thresholds=None, start_month=None, end_month=None):

    if thresholds is None:
        thresholds = [
            (60, 'S'),
            (45, 'A'),
            (30, 'B'),
            (15, 'C'),
            (0,  'D'),
        ]

    # 원본 보호: 복사본 사용
    data = df.copy()

    # 변환
    data['월'] = pd.to_datetime(data['월'].astype(str), format='%Y%m', errors='coerce')

    company_rows = data[data["거래처ID"] == company_name]

    if start_month:
        start_date = pd.to_datetime(start_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] >= start_date]
    if end_month:
        end_date = pd.to_datetime(end_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] <= end_date]

    number_list = company_rows['총환자수'].tolist()
    revenue_list = company_rows['매출'].tolist()

    if not revenue_list or sum(revenue_list) == 0:
        return '데이터없음'

    total_number = sum(number_list)
    total_revenue = sum(revenue_list)
    expected_revenue = total_number * 30000

    standard = (expected_revenue / total_revenue) * 100

    for figure, grade in thresholds:
        if standard >= figure:
            return grade

    return '에러'

#print(classify_company_by_rate_interaction(company_name="우리가족의원(강서구 가양동)", df=df, start_month=202402, end_month=202405))    *디버깅용(성공)

#############################################################################################################################################################
#############################################################################################################################################################

                                                                    # 최종등급선정

def classify_company_final(company_name, df, start_month=None, end_month=None):
    
    revenue_grade = classify_company_by_revenue_estimates(company_name, df, thresholds.revenue_threshold, start_month, end_month)
    print(revenue_grade)
    profit_grade = classify_company_by_profit(company_name, df, thresholds.profit_threshold, start_month, end_month)
    print(profit_grade)
    patience_grade = classify_company_by_number_patience(company_name, df, thresholds.patience_threshold, start_month, end_month)
    print(patience_grade)
    interaction_grade = classify_company_by_rate_interaction(company_name, df, thresholds.interaction_threshold, start_month, end_month)
    print(interaction_grade)

    if '데이터없음' in (revenue_grade, profit_grade, patience_grade, interaction_grade):
        return {
        "매출등급": revenue_grade,
        "이익률등급": profit_grade,
        "환자수등급": patience_grade,
        "상호작용등급": interaction_grade,
        "평균점수": None,
        "최종등급": "데이터부족"
    }
    
    
    grades = [revenue_grade, profit_grade, patience_grade, interaction_grade]
    scores = [map_grade_to_score(g) for g in grades]
    avg_score = sum(scores) / len(scores)
    final_grade = map_score_to_grade(avg_score)

    return {
        "매출등급": revenue_grade,
        "이익률등급": profit_grade,
        "환자수등급": patience_grade,
        "상호작용등급": interaction_grade,
        "평균점수": round(avg_score, 2),
        "최종등급": final_grade
    }

#print(classify_company_final(company_name="우리가족의원(강서구 가양동)", df=df, start_month=202402, end_month=202405))     *디버깅용(성공)
    
##############################################################################################################################################################   
##############################################################################################################################################################
                                                                    # 등급분류분석 레포트작성

async def generate_company_grade_report(company_name: str, grade_result: dict):

    prompt = f"""
당신은 기업 분석 전문가입니다.
아래는 '{company_name}'의 주요 성과 지표에 대한 등급 평가 결과입니다:

- 매출 등급: {grade_result.get("매출등급")}
- 이익률 등급: {grade_result.get("이익률등급")}
- 환자수 등급: {grade_result.get("환자수등급")}
- 상호작용 등급: {grade_result.get("상호작용등급")}
- 평균 점수: {grade_result.get("평균점수")}
- 최종 등급: {grade_result.get("최종등급")}

위 데이터를 기반으로, 이 회사가 왜 해당 등급을 받았는지 논리적으로 분석해 주세요.
각 항목의 의미와 상호 관련성을 포함해, 보고하는 형태의 리포트 형식으로 작성해 주세요.
"""

    response = await client.chat.completions.create(
        model="gpt-4o",  
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    return response.choices[0].message.content.strip()

##############################################################################################################################################################
##############################################################################################################################################################
                                                                # 거래처 성장분석 레포트작성
async def generate_growth_analysis_report(company_name, df):

    company_df = df[df['거래처ID'] == company_name]

    information = company_df[["월", "매출", "사용 예산", "총환자수"]].to_string(index=False)

    prompt = f"""
당신은 제약회사 영업 분석 전문가입니다.

'{company_name}' 거래처의 최근 활동 데이터를 기반으로, 다음 내용을 포함하는 성장 분석 보고서를 작성해 주세요:

- 월별 매출과 예산 사용 추이
- 환자수 변화에 따른 성장성
- 비용 대비 수익 구조
- 향후 개선 또는 확장 가능성
- 리스크 요인

데이터 샘플:
{information}

한글로 간결하지만 통찰력 있는 보고서를 작성해 주세요.
    """

    response = await client.chat.completions.create(
        model="gpt-4o",  
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    return response.choices[0].message.content.strip()

################################################################################################################################################################
#################################################################################################################################################################

                                                                    #거래처 영업전략 보고서 작성

async def generate_sales_strategy_report(company_name,grade_result: dict,start_month=None,end_month=None):

    data = df.copy()  
    data['월'] = data['월'].astype(str)  
    data['월'] = pd.to_datetime(data['월'], format='%Y%m', errors='coerce')
    company_rows = data[data["거래처ID"] == company_name] 

    if start_month:
        start_date = pd.to_datetime(start_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] >= start_date]
    if end_month:
        end_date = pd.to_datetime(end_month, format='%Y%m')
        company_rows = company_rows[company_rows['월'] <= end_date]

    if company_rows.empty:
        return f"{company_name}의 {start_month}~{end_month} 기간 데이터가 없습니다."

    essential_information = company_rows[["월", "매출", "사용 예산", "총환자수"]]
    information = essential_information.to_string(index=False)

    # 등급 결과 정리
    revenue = grade_result.get("매출등급", "N/A")
    profit = grade_result.get("이익률등급", "N/A")
    patience = grade_result.get("환자수등급", "N/A")
    interaction = grade_result.get("상호작용등급", "N/A")
    final_grade = grade_result.get("최종등급", "N/A")

    # 프롬프트
    prompt = f"""
당신은 제약회사의 영업전략 기획 전문가입니다.

아래는 거래처 '{company_name}'의 최근 {start_month}부터 {end_month}까지의 활동 데이터입니다:
{information}

성과 등급은 다음과 같습니다:
- 매출 등급: {revenue}
- 이익률 등급: {profit}
- 환자수 등급: {patience}
- 상호작용 등급: {interaction}
- 최종 등급: {final_grade}

이 정보를 기반으로 제약사 입장에서 취할 수 있는 영업 전략을 다음 항목으로 정리해 주세요:

1. 거래처의 현재 특성과 성과 요약
2. 주요 강점과 기회 요인
3. 리스크 또는 취약점
4. 제품 제안 전략, 커뮤니케이션 접근 방식
5. 단기/중기 전략 제안

간결하면서도 설득력 있게, 보고서 형식으로 작성해주세요. 한글로.
"""

    response = await client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    return response.choices[0].message.content.strip()

###############################################################################################################################################################
###############################################################################################################################################################
from langgraph.graph import StateGraph
from pydantic import BaseModel
from typing import Optional, Any, TypedDict

class ReportState(TypedDict):
    query: str
    company_name: str
    start_month: str
    end_month: str
    df: pd.DataFrame
    grade_result: dict
    grade_report: str
    growth_report: str
    strategy_report: str
    merged_report: str


async def parse_query_node(state):
    result = await parse_query_with_llm(state["query"])
    return {
        **state,
        "company_name": result["company_name"],
        "start_month": result["start_month"],
        "end_month": result["end_month"]
    }

def classify_node(state):
    company_name = state["company_name"]
    df = state["df"]
    start_month = state["start_month"]
    end_month = state["end_month"]

    grade_result = classify_company_final(company_name, df, start_month, end_month)
    return {"grade_result": grade_result}

async def grade_report_node(state):
    company_name = state["company_name"]
    grade_result = state["grade_result"]

    report = await generate_company_grade_report(company_name, grade_result)
    return {"grade_report": report}

async def growth_report_node(state):
    company_name = state["company_name"]
    df = state["df"]

    report = await generate_growth_analysis_report(company_name, df)
    return {"growth_report": report}

async def strategy_report_node(state):
    company_name = state["company_name"]
    grade_result = state["grade_result"]
    start_month = state["start_month"]
    end_month = state["end_month"]
    df = state["df"]

    report = await generate_sales_strategy_report(company_name, grade_result, start_month, end_month)
    return {"strategy_report": report}

def merged_report_node(state):
    grade = state["grade_result"]
    grade_report = state["grade_report"]
    growth = state["growth_report"]
    strategy = state["strategy_report"]

    merged = f"""
<등급>

{grade}

<등급 분석 레포트>

{grade_report}

<성장 분석 보고서>

{growth}

<영업 전략 보고서>

{strategy}
"""
    state["merged_report"] = merged.strip()
    return {"merged_report": merged.strip()}

builder = StateGraph(state_schema=ReportState)

builder.add_node("parse_query", parse_query_node)
builder.add_node("classify", classify_node)
builder.add_node("grade_report", grade_report_node)
builder.add_node("growth_report", growth_report_node)
builder.add_node("strategy_report", strategy_report_node)
builder.add_node("merged_report", merged_report_node)  

builder.set_entry_point("parse_query")
builder.add_edge("parse_query", "classify")
builder.add_edge("classify", "grade_report")

builder.add_edge("grade_report", "growth_report")
builder.add_edge("grade_report", "strategy_report")

builder.add_edge("growth_report", "merged_report")
builder.add_edge("strategy_report", "merged_report")

builder.set_finish_point("merged_report")

graph = builder.compile()

initial_state = {
    "query": "'우리가족의원(강서구 가양동)'에서 2024년 2월 부터 2024년5월까지의 실적을 분석해줘",
    "df": df  
}


if __name__ == "__main__":
    import asyncio

    async def main():
        result = await graph.ainvoke(initial_state)
        print("최종 보고서 출력 ===\n")
        print(result["merged_report"])

    asyncio.run(main())