"""Untitled74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3qyFxsXpT5UA247yerqFaQIUQnvwkVV
"""

COMPANIES = [
    {"name": "A전자", "sales": 1200, "visits": 58},
    {"name": "B테크", "sales": 1150, "visits": 51},
    {"name": "C디지털", "sales": 800, "visits": 32},
    {"name": "D산업", "sales": 390, "visits": 9},
    {"name": "E솔루션", "sales": 1300, "visits": 60},
    {"name": "F시스템", "sales": 1400, "visits": 65},
    {"name": "G하이텍", "sales": 720, "visits": 28},
    {"name": "H미디어", "sales": 950, "visits": 48},
    {"name": "I테크", "sales": 280, "visits": 5},
    {"name": "J전자부품", "sales": 450, "visits": 17}
]
import openai 
import os
from openai import AsyncOpenAI
client = AsyncOpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

async def classify_company(state):
    company = state["target_company"]
    sales = company["sales"]
    visits = company["visits"]
    name = company["name"]

    prompt = f"""
    업체 "{name}"의 실적은 다음과 같습니다:
    - 매출: {sales}만원
    - 방문 횟수: {visits}회

    다음 기준에 따라 이 업체를 A/B/C 등급 중 하나로 분류해주세요.

    [등급 기준]
    - A등급: 매출 1000만원 이상이고 방문 횟수 50회 이상
    - B등급: 매출 500~999만원이거나 방문 횟수 20~49회
    - C등급: 그 외의 경우

    등급만 한 글자로 답해주세요.
    """
    result = await client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )

    rating = result.choices[0].message.content
    return {"rating": rating}

async def generate_grade_report(state):
    company = state["target_company"]
    sales = company["sales"]
    visits = company["visits"]
    name = company["name"]
    rating = state["rating"]

    prompt = f"""
    업체 "{name}"의 실적은 다음과 같습니다:
    - 매출: {sales}만원
    - 방문 횟수: {visits}회

    [등급 기준]
    - A등급: 매출 1000만원 이상이고 방문 횟수 50회 이상
    - B등급: 매출 500~999만원이거나 방문 횟수 20~49회
    - C등급: 그 외의 경우

    이 업체가 {rating}등급으로 분류된 이유를 간단히 설명해주세요.
    매출과 방문 데이터를 기준으로 판단한 내용을 서술해주세요.
    """

    result = await client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )

    reason_report = result.choices[0].message.content
    return {"grade_reason_report": reason_report}

#state = {
#   "target_company": {
#        "name": "가상의 회사",
#        "sales": 1280,
#        "visits": 57
#    },
#    "rating": "A",
#    ...}

async def generate_sales_strategy_report(state):
    company = state["target_company"]
    name = company["name"]
    sales = company["sales"]
    visits = company["visits"]
    rating = state.get("rating", "C")

    prompt = f"""
    당신은 제약회사 고객을 상대하는 영업 전략가입니다.

    다음은 대상 업체의 정보입니다:
    업체명: {name}
    매출: {sales}만원
    방문 횟수: {visits}회
    고객 등급: {rating}

    이 업체를 대상으로 한 향후 영업 전략 보고서를 작성해주세요.

    [요구사항]
    업체의 현재 상황을 간단히 진단
    등급/실적에 따른 맞춤형 접근 전략 제안
    주기적인 방문/제안/자료 제공 등의 구체적 행동 전략 포함
    단락 구분이 명확한 간단한 문서 형식
    줄바꿈 없이, 한 문단 형식으로 서술
    """

    result = await client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )

    report = result.choices[0].message.content
    return {"sales_strategy_report": report}

async def generate_growth_summary_report(state):
    company = state["target_company"]
    name = company["name"]
    sales = company["sales"]
    visits = company["visits"]
    rating = state.get("rating", None)

    prompt = f"""
    당신은 제약회사의 영업기획팀 소속 데이터 분석가입니다.

    다음은 자사와 거래 중인 특정 거래처의 최근 실적 정보입니다:
    거래처명: {name}
    매출: {sales}만원
    방문 횟수: {visits}회

    [분석 요청]
    1. 거래처의 현재 실적 상황을 간결하게 요약해 주세요.
    2. 매출 및 방문 이력을 기반으로 거래 관계의 강도와 현황을 평가해 주세요.
    3. 해당 거래처의 향후 성장 가능성을 분석해 주세요.
    4. 자사 입장에서 어떤 방식의 대응 또는 전략적 접근이 필요한지 제언해 주세요.
    5. 전문 리포트 형식으로 작성해 주세요.
    6. 줄바꿈 없이, 한 문단 형식으로 서술해주세요
    """

    result = await client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )

    report = result.choices[0].message.content
    return {"growth_summary_report": report}

async def merge_reports(state):
    strategy = state.get("sales_strategy_report", "")
    growth = state.get("growth_summary_report", "")

    merged = f"""
    [통합 보고서]

    영업 전략 보고서
    {strategy.strip()}

    실적 요약 및 성장 분석
    {growth.strip()}
    """
    return {"merged_report": merged}


from langgraph.graph import StateGraph, END
from typing import TypedDict

class State(TypedDict, total=False):
    target_company: dict
    rating: str
    grade_reason_report: str
    sales_strategy_report: str
    growth_summary_report: str
    merged_report: str


builder = StateGraph(State)
builder.add_node("classify_company", classify_company)
builder.add_node("generate_grade_report", generate_grade_report)
builder.add_node("generate_sales_strategy_report", generate_sales_strategy_report)
builder.add_node("generate_growth_summary_report", generate_growth_summary_report)
builder.add_node("merge_reports", merge_reports)

builder.set_entry_point("classify_company")

builder.add_edge("classify_company", "generate_grade_report")
builder.add_edge("generate_grade_report", "generate_sales_strategy_report")
builder.add_edge("generate_grade_report", "generate_growth_summary_report")

builder.add_edge("generate_sales_strategy_report", "merge_reports")
builder.add_edge("generate_growth_summary_report", "merge_reports")

builder.add_edge("merge_reports", END)

graph = builder.compile()

# API 호환성을 위한 ClientAnalysisAgent 클래스 추가
class ClientAnalysisAgent:
    """고객 분석 에이전트 클래스"""
    
    def __init__(self):
        self.graph = graph
        self.companies = COMPANIES
    
    def analyze_client(self, client_name: str, sales: int = None, visits: int = None):
        """고객 분석 수행"""
        try:
            # 기존 회사 데이터에서 찾기
            company_data = None
            for company in self.companies:
                if client_name in company["name"] or company["name"] in client_name:
                    company_data = company
                    break
            
            # 새로운 데이터로 덮어쓰기 (제공된 경우)
            if company_data is None:
                company_data = {"name": client_name, "sales": sales or 500, "visits": visits or 20}
            else:
                if sales is not None:
                    company_data["sales"] = sales
                if visits is not None:
                    company_data["visits"] = visits
            
            # 분석 실행 (동기 버전으로 간소화)
            result = self._sync_analyze(company_data)
            return result
            
        except Exception as e:
            print(f"고객 분석 오류: {e}")
            return self._get_dummy_result(client_name)
    
    def _sync_analyze(self, company_data):
        """동기 분석 (더미 데이터 기반)"""
        name = company_data["name"]
        sales = company_data["sales"]
        visits = company_data["visits"]
        
        # 등급 분류
        if sales >= 1000 and visits >= 50:
            rating = "A"
        elif sales >= 500 or visits >= 20:
            rating = "B"
        else:
            rating = "C"
        
        # 보고서 생성
        grade_reason = f"{name}은(는) 매출 {sales}만원, 방문 {visits}회로 {rating}등급에 해당합니다."
        
        strategy_report = f"{name}에 대한 영업 전략: {rating}등급 고객으로서 {'프리미엄 서비스' if rating == 'A' else '표준 서비스' if rating == 'B' else '기본 서비스'}를 제공하며, {'월 2회' if rating == 'A' else '월 1회' if rating == 'B' else '분기 1회'} 정기 방문을 통해 관계를 강화해야 합니다."
        
        growth_summary = f"{name}의 성장 분석: 현재 실적을 바탕으로 {'높은' if rating == 'A' else '중간' if rating == 'B' else '낮은'} 성장 잠재력을 보이고 있으며, {'확대 투자' if rating == 'A' else '안정적 관리' if rating == 'B' else '최소 유지'}가 권장됩니다."
        
        merged_report = f"""[통합 보고서]

영업 전략 보고서
{strategy_report}

실적 요약 및 성장 분석
{growth_summary}"""
        
        return {
            "target_company": company_data,
            "rating": rating,
            "grade_reason_report": grade_reason,
            "sales_strategy_report": strategy_report,
            "growth_summary_report": growth_summary,
            "merged_report": merged_report
        }
    
    def _get_dummy_result(self, client_name):
        """더미 결과 반환"""
        return {
            "target_company": {"name": client_name, "sales": 800, "visits": 35},
            "rating": "B",
            "grade_reason_report": f"{client_name}은(는) 중간 등급 고객입니다.",
            "sales_strategy_report": f"{client_name}에 대한 표준 영업 전략을 적용합니다.",
            "growth_summary_report": f"{client_name}의 성장 잠재력은 보통 수준입니다.",
            "merged_report": f"[통합 보고서]\n\n{client_name}에 대한 종합 분석 결과입니다."
        }