"""recreate_table_descriptions

Revision ID: 2273a3c6233f
Revises: 65c0a9bfbd6a
Create Date: 2025-08-06 18:10:18.741139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '2273a3c6233f'
down_revision: Union[str, Sequence[str], None] = '65c0a9bfbd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # pgvector 확장 활성화
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # table_descriptions 테이블 생성 (벡터 유사도 검색용)
    op.create_table('table_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', VECTOR(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name', name='uq_table_descriptions_table_name')
    )
    
    # 벡터 인덱스 생성
    op.execute('CREATE INDEX idx_table_descriptions_embedding ON table_descriptions USING ivfflat (embedding vector_cosine_ops)')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_descriptions')
    # ### end Alembic commands ###
