"""리비fix sales_recodes

Revision ID: 65c0a9bfbd6a
Revises: e9c98ba4ed5f
Create Date: 2025-08-06 17:54:22.805496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65c0a9bfbd6a'
down_revision: Union[str, Sequence[str], None] = 'e9c98ba4ed5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_table_descriptions_embedding'), table_name='table_descriptions', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_table('table_descriptions')
    op.alter_column('sales_records', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_records', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('sales_records_customer_id_fkey'), 'sales_records', type_='foreignkey')
    op.drop_constraint(op.f('sales_records_employee_id_fkey'), 'sales_records', type_='foreignkey')
    op.create_foreign_key(None, 'sales_records', 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales_records', 'employee_info', ['employee_id'], ['employee_info_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_records', type_='foreignkey')
    op.drop_constraint(None, 'sales_records', type_='foreignkey')
    op.create_foreign_key(op.f('sales_records_employee_id_fkey'), 'sales_records', 'employee_info', ['employee_id'], ['employee_info_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('sales_records_customer_id_fkey'), 'sales_records', 'customers', ['customer_id'], ['customer_id'], ondelete='SET NULL')
    op.alter_column('sales_records', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_records', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('table_descriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sample_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('table_descriptions_pkey')),
    sa.UniqueConstraint('table_name', name=op.f('uq_table_descriptions_table_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_table_descriptions_embedding'), 'table_descriptions', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
