"""Add branches and branch_targets tables, refactor employee_info

Revision ID: 846206dde9cc
Revises: 2273a3c6233f
Create Date: 2025-08-11 07:31:48.513276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846206dde9cc'
down_revision: Union[str, Sequence[str], None] = '2273a3c6233f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('branch_id', sa.Integer(), nullable=False, comment='지점 ID'),
    sa.Column('headquarters', sa.String(length=100), nullable=False, comment='본부'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='부서'),
    sa.Column('branch_name', sa.String(length=100), nullable=False, comment='지점명'),
    sa.Column('contact_number', sa.String(length=20), nullable=True, comment='연락처'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='상태 (active/inactive)'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('branch_name')
    )
    op.create_index(op.f('ix_branches_branch_id'), 'branches', ['branch_id'], unique=False)
    op.create_table('branch_targets',
    sa.Column('target_id', sa.Integer(), nullable=False, comment='목표 ID'),
    sa.Column('branch_id', sa.Integer(), nullable=False, comment='지점 ID'),
    sa.Column('employee_info_id', sa.Integer(), nullable=False, comment='직원 인사정보 ID'),
    sa.Column('target_year', sa.Integer(), nullable=False, comment='목표 년도'),
    sa.Column('target_month', sa.Integer(), nullable=False, comment='목표 월'),
    sa.Column('target_date', sa.Date(), nullable=False, comment='목표 년월 (YYYY-MM-01)'),
    sa.Column('target_amount', sa.Float(), nullable=True, comment='목표 금액'),
    sa.Column('actual_amount', sa.Float(), nullable=True, comment='실적 금액'),
    sa.Column('achievement_rate', sa.Float(), nullable=True, comment='달성률 (%)'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['employee_info_id'], ['employee_info.employee_info_id'], ),
    sa.PrimaryKeyConstraint('target_id'),
    sa.UniqueConstraint('branch_id', 'employee_info_id', 'target_year', 'target_month', name='uq_branch_employee_yearmonth')
    )
    op.create_index(op.f('ix_branch_targets_target_id'), 'branch_targets', ['target_id'], unique=False)
    op.drop_index(op.f('idx_table_descriptions_embedding'), table_name='table_descriptions', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_table('table_descriptions')
    op.add_column('employee_info', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee_info', 'branches', ['branch_id'], ['branch_id'])
    op.drop_column('employee_info', 'team')
    op.drop_column('employee_info', 'business_unit')
    op.drop_column('employee_info', 'branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_info', sa.Column('business_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_info', sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_info', type_='foreignkey')
    op.drop_column('employee_info', 'branch_id')
    op.create_table('table_descriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sample_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('table_descriptions_pkey')),
    sa.UniqueConstraint('table_name', name=op.f('uq_table_descriptions_table_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_table_descriptions_embedding'), 'table_descriptions', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_branch_targets_target_id'), table_name='branch_targets')
    op.drop_table('branch_targets')
    op.drop_index(op.f('ix_branches_branch_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
