"""add_document_processing_fields

Revision ID: e9c98ba4ed5f
Revises: c5a0631f39b3
Create Date: 2025-08-06 09:31:26.214676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9c98ba4ed5f'
down_revision: Union[str, Sequence[str], None] = 'c5a0631f39b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_metadata')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
